---
# Organization to pull metrics from
organization: 'github'

# Start date to pull metrics from
since: '2023-05-01'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/metrics'
